imageCredentials:
  dockerconfig: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJyYWphc2hyZWVqIiwicGFzc3dvcmQiOiJkb2NrZXJodWJwd2Q4OCIsImVtYWlsIjoicmFqYXNocmVlam9zaGk4QGdtYWlsLmNvbSIsImF1dGgiOiJjbUZxWVhOb2NtVmxhanBrYjJOclpYSm9kV0p3ZDJRNE9BPT0ifX19
  username: <docker_username>
  password: <docker_password>
  email: <docker_email>
  registry: https://index.docker.io/v1/

spec:
  imageName: rajashreej/csye7125:latest
  appName: webapp
  replicaCount: 3
  progressDeadlineSeconds: 60
  minReadySeconds: 30
  strategy:
    maxSurge: 1
    maxUnavailable: 0
    type: RollingUpdate

nodeSelector: {}

tolerations: []

affinity: {}
