apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.spec.appName }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
